Issue #2038355 - Fix for error when issuing a river flood warning
- When issuing a river flood warning, an unhandled event loop error would pop up in alertviz with the cause in the stacktrace being:
java.lang.NoClassDefFoundError: jakarta/transaction/SystemException
- It was found that jakarta.transaction was on the classpath and the issue was caused by a problem in the class lookup logic in jboss-logging.
- The class lookup logic has been updated in later versions of jboss-logging that makes it more compatible with java 17 and the module system.

Change-Id: I8f174e2165fa44ef341fe0386ec053fc4b44d3d8